name: Build and Deploy Vite App

# 触发条件：推送到 main 分支时执行
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境
    permissions:
      contents: write  # 允许写入仓库内容（包括推送分支）
    steps:
      # 1. 检出代码仓库
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整历史，避免构建时出现 Git 信息缺失

      # 2. 设置 Node.js 环境（VitePress 需要 Node.js 18+）
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22  # 推荐使用 Node.js 18 及以上
          cache: 'npm'  # 缓存 npm 依赖，加速安装

      # 3. 安装项目依赖
      - name: Install dependencies
        run: npm ci  # 比 npm install 更严格，优先使用 package-lock.json

      # 4. 打包 Vite 项目（关键步骤）
      - name: Build Vite app
        run: npm run build  # 确保 package.json 中有 "build": "vite build" 脚本
      # 5. 部署到 GitHub Pages
      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # 成熟的 GitHub Pages 部署工具
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的 GitHub 令牌（无需手动配置）
          publish_dir: ./example/dist  # VitePress 构建输出目录（默认路径）
          force_orphan: true  # 强制创建孤立分支（避免历史提交过大）
